// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUd0F3mOIKDbLInGp1haYG_872iZNwjFA',
    appId: '1:164638049802:web:2f476f07c4b4ad971e41f3',
    messagingSenderId: '164638049802',
    projectId: 'turnofacil-app-2025',
    authDomain: 'turnofacil-app-2025.firebaseapp.com',
    storageBucket: 'turnofacil-app-2025.firebasestorage.app',
    measurementId: 'G-57WZHBSTCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0xZHdNtPZq6SmasozPHz_Mpo4vZiKRKk',
    appId: '1:164638049802:android:0069d4aa2be298391e41f3',
    messagingSenderId: '164638049802',
    projectId: 'turnofacil-app-2025',
    storageBucket: 'turnofacil-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQGOUZjvHWZGlEmQ9VO-JWFSgd1yBGaY',
    appId: '1:164638049802:ios:31d884832e7f683b1e41f3',
    messagingSenderId: '164638049802',
    projectId: 'turnofacil-app-2025',
    storageBucket: 'turnofacil-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.turnofacilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQGOUZjvHWZGlEmQ9VO-JWFSgd1yBGaY',
    appId: '1:164638049802:ios:31d884832e7f683b1e41f3',
    messagingSenderId: '164638049802',
    projectId: 'turnofacil-app-2025',
    storageBucket: 'turnofacil-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.turnofacilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUd0F3mOIKDbLInGp1haYG_872iZNwjFA',
    appId: '1:164638049802:web:e72af8b66ed042361e41f3',
    messagingSenderId: '164638049802',
    projectId: 'turnofacil-app-2025',
    authDomain: 'turnofacil-app-2025.firebaseapp.com',
    storageBucket: 'turnofacil-app-2025.firebasestorage.app',
    measurementId: 'G-BCH9B24P26',
  );
}
